name: hongsamIDE-backend-was CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULE_KEY }}
        submodules: recursive
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: hongsamIDE-back-was
        path: build/libs/was-0.0.1-SNAPSHOT.jar

  # 배포 
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: hongsamIDE-back-was
        path: build/libs/
        
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/was-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_HOST }}@${{ secrets.EC2_IP }}:/home/${{ secrets.EC2_HOST }}/hongsamIDE-back-was.jar
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }}@${{ secrets.EC2_IP }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_HOST }}/hongsamIDE-back-was.jar > app.log 2>&1 &"
        rm -f private_key.pem
